apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-applaunchpad
  namespace: tolabs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-applaunchpad
rules:
  - apiGroups: ['*']
    resources: [ '*' ]
    verbs: [ '*' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-applaunchpad-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sa-applaunchpad
subjects:
  - kind: ServiceAccount
    name: sa-applaunchpad
    namespace: tolabs
